name: Build and Scan Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout

jobs:
  build_and_scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: List Files
        run: ls -la docker

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Build Docker image
        run: |
          docker build -t my-image:latest -f docker/Dockerfile .

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Scan Docker image for vulnerabilities
        run: |
          snyk test --docker my-image:latest --severity-threshold=low --json > snyk-result.json || { echo 'Snyk scan failed'; cat snyk-result.json; exit 1; }
